name: Cucumber

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ truffleruby-head ]
        engine: [ --engine.Mode=latency ]
        regexengine: [--use-truffle-regex=false, --use-truffle-regex=true]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -f Dockerfile-${{matrix.ruby}} -t after-bundle-install:latest .
    - run: docker build -f Dockerfile-after-bundle-install -t after-assets-precompile:latest .
    - run: docker build -f Dockerfile-after-assets-precompile -t school-experience:latest .
    - name: set RUBYOPT for truffleruby
      if: matrix.ruby == 'truffleruby-head'
      run : |
        cat > .env << EOL
        RUBYOPT_SCHOOL_EXPERIENCE=--experimental-options ${{matrix.engine}} ${{matrix.regexengine}}
        RUBYOPT_DELAYED_JOBS=--experimental-options --engine.Compilation=false
        RUBYOPT_DB_TASKS=--experimental-options --engine.Compilation=false
        EOL
        cat > cucumber.env << EOL
        RUBYOPT_CUCUMBER=--experimental-options\ ${{matrix.regexengine}}\ ${{matrix.engine}}
        EOL
    - run: docker-compose -f docker-compose.yml -f docker-compose-chrome.yml pull postgres redis selenium-chrome
    - name: spin up
      run : |
        docker-compose -f docker-compose.yml -f docker-compose-chrome.yml config
        docker-compose -f docker-compose.yml -f docker-compose-chrome.yml up -d
        WAIT_COUNT=0
        until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 48 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
    - name: run specs for truffleruby
      run: |
        [[ -e cucumber.env ]] && source cucumber.env
        echo "RUBYOPT_CUCUMBER=${RUBYOPT_CUCUMBER}"
        docker-compose -f docker-compose.yml \
                       -f docker-compose-chrome.yml run --rm \
                       -e RAILS_ENV=test \
                       -e SELENIUM_HUB_HOSTNAME=selenium-chrome \
                       -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true \
                       -e APP_URL=http://school-experience:3000 \
                       -e CUC_DRIVER=chrome \
                       -e RUBYOPT="${RUBYOPT_CUCUMBER}" \
                       --no-deps school-experience cucumber 
        echo 'completed cucumber tests'
