name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mri, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -f Dockerfile-${{matrix.ruby}} -t school-experience:latest .
    - name: spin up
      run : |
        docker-compose up -d
        WAIT_COUNT=0
        until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 12 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
    - name: run specs
      run: docker-compose run --rm db-tasks rspec --format progress --format RspecJunitFormatter --out /ci_build/rspec_results.xml
    
