name: Cucumber

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mri, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -f Dockerfile-${{matrix.ruby}} -t school-experience:latest .
    - name: spin up
      run : |
        docker-compose -f docker-compose.yml -f docker-compose-chrome.yml up -d
        WAIT_COUNT=0
        until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 48 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
    - name: run specs
      run: |
        docker-compose -f docker-compose.yml \
                       -f docker-compose-chrome.yml run --rm \
                       -e RAILS_ENV=test \
                       -e SELENIUM_HUB_HOSTNAME=selenium-chrome \
                       -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true \
                       -e APP_URL=http://school-experience:3000 \
                       -e CUC_DRIVER=chrome \
                       -e RUBYOPT='--experimental-options --engine.Mode=latency' \
                       --no-deps school-experience cucumber
    
