name: Ruby

on:
  push:
    branches:    
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '46 4 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mri, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -f Dockerfile-${{matrix.ruby}} -t school-experience:latest .
    - name: spin up
      run : |
        docker-compose up -d
        WAIT_COUNT=0
        until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 48 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
    - name: run a spec with profiling
      if: matrix.ruby == 'truffleruby-head'
      run: |
        docker-compose run \
              -e RUBYOPT='--experimental-options --cpusampler --cpusampler.OutputFile=sampling.json --cpusampler.SampleInternal --cpusampler.Mode=roots --cpusampler.Output=json' \
              --no-deps \
              --rm db-tasks rspec spec/controllers/schools/placement_dates/subject_selections_controller_spec.rb
        ls -l sampling.json
        rm sampling.json
    - name: run specs
      run: docker-compose run --no-deps --rm db-tasks rspec --format progress --format RspecJunitFormatter --out /ci_build/rspec_results.xml
